version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
     - postgresql_data:/var/lib/postgresql/data/

volumes:
  postgresql_data:
